import { useTranslation } from 'react-i18next'
import { formatSuggestion } from '@/lib/geo'
import { usePatientFinder } from '@/hooks/usePatientFinder'
import EmergencyBanner from '@/components/EmergencyBanner'

function AvailabilityPill({ tier }: { tier: 'high' | 'moderate' | 'low' | 'full' | 'unknown' }) {
  const { t } = useTranslation()
  
  const config = {
    high: { label: t('High availability'), className: 'bg-emerald-100 text-emerald-800' },
    moderate: { label: t('Moderate availability'), className: 'bg-amber-100 text-amber-800' },
    low: { label: t('Low availability'), className: 'bg-red-100 text-red-800' },
    full: { label: t('Full'), className: 'bg-slate-200 text-slate-600' },
    unknown: { label: t('Unknown'), className: 'bg-slate-100 text-slate-500' },
  }[tier]

  return (
    <span className={`mt-1 inline-block rounded-full px-2.5 py-0.5 font-label text-xs font-medium ${config.className}`}>
      {config.label}
    </span>
  )
}

export default function PatientFinder() {
  const { t } = useTranslation()
  const { ranked, loading, error, findNearby } = usePatientFinder()

  return (
    <div className="min-h-screen bg-paper font-body text-ink">
      <EmergencyBanner />
      {/* Ambient signature: local dots rising into aggregated nodes */}
      <div className="pointer-events-none absolute inset-x-0 top-0 h-72 overflow-hidden opacity-40">
        <svg viewBox="0 0 400 200" className="h-full w-full">
          {[...Array(12)].map((_, i) => (
            <circle
              key={i}
              cx={30 + (i % 6) * 65}
              cy={180}
              r="3"
              fill="#1B6E75"
              className="animate-rise"
              style={{ animationDelay: `${i * 0.4}s` }}
            />
          ))}
          <circle cx="200" cy="20" r="8" fill="#E8A33D" opacity="0.6" />
        </svg>
      </div>

      <div className="relative mx-auto max-w-xl px-6 pt-20 pb-12">
        <p className="mb-2 font-label text-xs uppercase tracking-wider text-primary-light">
          {t('PHC Federated Platform')}
        </p>
        <h1 className="mb-3 font-display text-4xl font-semibold leading-tight text-primary">
          {t('Find a nearby health centre')}
        </h1>
        <p className="mb-8 text-base text-ink/70">
          {t("We'll suggest the closest PHC with beds available, based on your current location.")}
        </p>

        <button
          onClick={findNearby}
          disabled={loading}
          className="rounded-lg bg-primary px-6 py-3 text-sm font-medium text-paper shadow-sm transition hover:bg-primary-dark disabled:opacity-50"
        >
          {loading ? t('Finding facilities…') : t('Find nearby facility')}
        </button>

        {/* Note: error is dynamically generated by your hook, so it remains unwrapped to prevent breaking logic */}
        {error && (
          <p className="mt-4 rounded-lg bg-critical/10 px-4 py-3 text-sm text-critical">{error}</p>
        )}

        {ranked.length > 0 && (
          <div className="mt-8 space-y-4">
            <div className="rounded-xl border border-accent/30 bg-accent/10 p-4">
              <p className="font-label text-xs uppercase tracking-wide text-accent-dark">
                {t('Recommended')}
              </p>
              {/* Note: formatSuggestion operates on backend logic, so we leave it un-wrapped */}
              <p className="mt-1 text-sm text-ink">{formatSuggestion(ranked)}</p>
            </div>

            <div className="space-y-2">
              {ranked.slice(0, 5).map((r) => (
                <div
                  key={r.facility.facility_id}
                  className="rounded-lg border border-primary/10 bg-white px-4 py-3 shadow-sm"
                >
                  <div className="flex items-center justify-between">
                    <div>
                      <div className="font-medium text-ink">{r.facility.name_en}</div>
                      <div className="font-devanagari text-xs text-ink/50">{r.facility.name_hi}</div>
                    </div>
                    <div className="text-right">
                      <div className="font-label text-sm text-ink">{r.distanceKm.toFixed(1)} {t('km')}</div>
                      <AvailabilityPill tier={r.facility.availability_tier} />
                    </div>
                  </div>

                  <a
                    href={`https://www.google.com/maps/dir/?api=1&destination=${r.facility.lat},${r.facility.lng}`}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="mt-3 flex items-center gap-1.5 text-xs font-medium text-primary-light hover:text-primary"
                  >
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" className="h-3.5 w-3.5">
                      <path fillRule="evenodd" d="M15.312 11.424a5.5 5.5 0 01-9.201 2.466l-.312-.311h2.433a.75.75 0 000-1.5H3.989a.75.75 0 00-.75.75v4.242a.75.75 0 001.5 0v-2.43l.31.31a7 7 0 0011.712-3.138.75.75 0 00-1.449-.39zm1.23-3.723a.75.75 0 00.219-.53V2.929a.75.75 0 00-1.5 0V5.36l-.31-.31A7 7 0 003.239 8.188a.75.75 0 101.448.389A5.5 5.5 0 0113.89 6.11l.311.31h-2.432a.75.75 0 000 1.5h4.243a.75.75 0 00.53-.219z" clipRule="evenodd" />
                    </svg>
                    {t('Get directions')}
                  </a>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
      {/* Ambient red glow from below */}
      <div
        className="pointer-events-none fixed inset-x-0 bottom-0 h-64 opacity-70"
        style={{
          background: 'radial-gradient(ellipse at bottom, #C4453D 0%, transparent 70%)',
          filter: 'blur(40px)',
        }}
      />
    </div>
  )
}